services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: es01
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9302:9302"
    volumes:
      - es-data-es01:/usr/share/elasticsearch/data
  
  api:
    build: ./api
    container_name: api
    depends_on:
      es01:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOST=http://es01:9200
    ports:
      - "8000:8000"
    volumes:
      - models:/api/models
  
  db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=stiigp
      - POSTGRES_PASSWORD=recsys
      - POSTGRES_DB=recsys
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stiigp -d recsys || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./frontend
      # CHANGE INTO NORMAL DOCKERFILE BEFORE GOING PROD
      # dockerfile: Dockerfile.dev
      args:
        - API_URL=http://api:8000
    container_name: frontend
    depends_on:
      api:
        condition: service_started
    ports:
      - "3000:80"
    #   - "3001:5173"

    # # DELETE THESE VOLUMES BEFORE GOING PROD
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules

volumes:
  es-data-es01:
  pgdata:
  models:
